name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./catalog-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service
      IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image \
            -Dspring-boot.build-image.image.name=${DOCKER_IMAGE_NAME} \
            -Dspring-boot.build-image.image.tags=${IMAGE_TAG} \
            -DskipTests
          echo "Verifying the built image..."
          docker images | grep "${DOCKER_IMAGE_NAME}:${IMAGE_TAG}" || exit 1
          echo "Pushing image ${DOCKER_IMAGE_NAME}:${IMAGE_TAG}..."
          docker push ${DOCKER_IMAGE_NAME}:${IMAGE_TAG}
